set(BOOST_LIB /workspaces/nextpnr-xilinx/build-wasm/boost-wasm/lib)
set(Boost_FOUND TRUE)
set(Boost_INCLUDE_DIRS /workspaces/nextpnr-xilinx/build-wasm/boost-wasm/include)
set(Boost_LIBRARY_DIRS ${BOOST_LIB})
foreach(lib filesystem program_options iostreams system)
    string(TOUPPER ${lib} LIB)
    set(Boost_${LIB}_LIBRARY ${BOOST_LIB}/libboost_${lib}.a)
    set(Boost_${LIB}_LIBRARY_RELEASE ${BOOST_LIB}/libboost_${lib}.a)
    list(APPEND Boost_LIBRARIES ${BOOST_LIB}/libboost_${lib}.a)
endforeach()
set(Boost_VERSION "1.83.0")
set(Boost_VERSION_STRING "1.83.0")
